### ISSUE TITLE
Share the training info

### ISSUE THREAD

**Issue by jiahao42** [aobo-y/SouthPark-Chatbot#41]
Please share what you have tried here.

**Comment by aobo-y** [comment]
- 40 persona, LSTM
- 100 persona, LSTM, max length 40

**Comment by jiahao42** [comment]
```
RNN_TYPE = 'GRU'
PERSONA_SIZE = 80
MAX_LENGTH = 30  # Maximum sentence length to consider
```
Also, I trimmed all the punctuations in the questions.

**Comment by jiahao42** [comment]
* RNN_TYPE = 'GRU'
* PERSONA_SIZE = 100
* MAX_LENGTH = 30

Also, I trimmed all the punctuations in the questions.

**Comment by jiahao42** [comment]
* RNN_TYPE = 'GRU'
* PERSONA_SIZE = 100
* MAX_LENGTH = 20  # Maximum sentence length to consider

Also, I trimmed all the punctuations in the questions.

**Comment by ddddwy** [comment]
## Ongoing

**1**
RNN_TYPE = 'LSTM'
PERSONA_SIZE = 300
MAX_LENGTH = 20
Pretrain_iter = 150k
Finetune_iter = 15k

 **2**
RNN_TYPE = 'GRU'
PERSONA_SIZE = 300
MAX_LENGTH = 20
Pretrain_iter = 50k
Finetune_iter = 10k
tf_rate = 1
